### PR TITLE
VAN-3280 Fix typo in Borat landing page

### PR DESCRIPTION
**Pull request by dshelley66**
The word visitor was misspelled in the index.html.

Also added a docker-compose.yml file so that one can run the app
locally for testing.

### CODE REVIEW

**Comment by kanaksinghal** [comment]
the code seems to have the same typo at two more places. although it's just variable names.
image

**Review by kanaksinghal — DISMISSED** [review]

**Comment by dshelley66** [comment]
> the code seems to have the same typo at two more places. although it's just variable names. image

Good catch - this is now fixed.

**Review by shwetanshu-cldcvr — APPROVED** [review]
LGTM

**Pull request merged**
